### ISSUE TITLE
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by pysnow530** [privatenumber/playwright-start#4]
## Bug description

`npx playwright-start` failed, it saids:

```
/Users/xxx/.npm/_npx/7d976fb7a2568a32/node_modules/playwright-start/dist/playwright-start.js:49
    [parsed.options.headless] = parsed.options.headless;
                              ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at /Users/xxx/.npm/_npx/7d976fb7a2568a32/node_modules/playwright-start/dist/playwright-start.js:49:31
    at Object.<anonymous> (/Users/xxx/.npm/_npx/7d976fb7a2568a32/node_modules/playwright-start/dist/playwright-start.js:64:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/xxx/.npm/_npx/7d976fb7a2568a32/node_modules/playwright-start/bin/playwright-start.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)

Node.js v18.0.0
```

## Reproduction steps

`npx playwright-start`

## Environment

- `playwright-start` version: 

➜  ~ npx playwright-start --version
start-browser/1.1.0 darwin-x64 node-v18.0.0

- Operating System:

Darwin xxx-MB0 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

- Node version: v18.0.0

- Package manager (npm/yarn/pnpm) and version: npx 8.6.0

**Comment by erikrichardlarson** [comment]
You should be able to avoid this error by passing `--headless=false` or `--headless=true`
